### PR TITLE
Fix: Correctly quote table names

### LINKED ISSUE #524: Unquoted table names causes issue when table has reserved sql keyword
### Environment
- Platform+version: **iOS 14.x**
- FLEX version: **4.4.1** 

### Bug Report

https://github.com/FLEXTool/FLEX/blob/258ec8697bf9c703390b0994899d94e289406c63/Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m#L117-L119

The name of my table is `order`, causing the following statement from my sql logging:
`near "order": syntax error in "SELECT * FROM order"`

The correct statement should read `SELECT * FROM "order"`

### PR DESCRIPTION
**Pull request by mgray88**
Sqlite is often smart enough to not need quotes for identifiers, unless you want to use a keyword as a name. Then you need to quote it

https://www.sqlite.org/lang_keywords.html

Fixes #524

### CODE REVIEW

**Comment by NSExceptional** [comment]
Thanks! Could you do me a favor and break the command string out into it's own variable on a new line?

**Comment by mgray88** [comment]
@NSExceptional Like just `tableName` similar to how it was before?

```
return [self executeStatement:[NSString stringWithFormat:@"SELECT * FROM \"%@\"",
    tableName
]].rows ?: @[];
```

**Comment by NSExceptional** [comment]
Nah, hang on, let me do a formal code suggestion

File: Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m [hunk 1]
```diff
@@ -114,9 +114,7 @@ - (NSInteger)lastRowID {
 }
 
 - (NSArray<NSArray *> *)queryAllDataInTable:(NSString *)tableName {
-    return [self executeStatement:[@"SELECT * FROM "
-        stringByAppendingString:tableName
-    ]].rows ?: @[];
+    return [self executeStatement:[NSString stringWithFormat:@"SELECT * FROM \"%@\"", tableName]].rows ?: @[];
```
Comment (NSExceptional) [inline Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m:117]:
```suggestion
    NSString *command = [NSString stringWithFormat:@"SELECT * FROM \"%@\"", tableName];
    return [self executeStatement:command].rows ?: @[];
```

Comment (mgray88) [reply Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m:117]: Gotcha. That was my other interpretation :)
